### ISSUE TITLE
Error with Jewelcrafting in Cata Classic

### ISSUE THREAD

**Issue by tehKD** [Shape-addons/ProfessionCooldown#13]
Im getting this error with the latest update:

4x ProfessionCooldown/pcd.lua:189: attempt to compare number with nil
[string "@ProfessionCooldown/pcd.lua"]:189: in function `GetCooldownsFromSpellIds'
[string "@ProfessionCooldown/pcd.lua"]:62: in function `UpdateCds'
[string "@ProfessionCooldown/pcd.lua"]:43: in function <ProfessionCooldown/pcd.lua:31>

Locals:
charName = "*****:*****"
jcSkill = 525
(*temporary) = nil
(*temporary) = "icy prism"
(*temporary) = "jewelcrafting"
(*temporary) = 62242
(*temporary) = 1719129234.491000
(*temporary) = "attempt to compare number with nil"

**Comment by nieejl** [comment]
Hi, thank you for reporting. I will look into it.

**Comment by nieejl** [comment]
Should be solved with version 1.23.
Please reopen the issue if it persists.
