### ISSUE TITLE
[bug] Filter options 

### ISSUE THREAD

**Issue by DanyRahm** [Shape-addons/ProfessionCooldown#14]
Hey, when using the /pcd filter, there seems to be a bug happening with the global removal box.

To reproduce:
1. tick global to display all cooldowns
2. untick global to remove all cooldowns
3. tick a single cooldown
result: all cooldowns of the selected profession from step 3 will be displayed

https://imgur.com/a/HQXra8M

**Comment by nieejl** [comment]
Hi,
Yes, I realized I broke some filter functionality when I made the cataclysm version.
I will try to have a fix one of the coming days, if not tonight.
