### ISSUE TITLE
WOW Classic lua error pcd.lua:398: attempt to index local 'skillName' (a nil value)

### ISSUE THREAD

**Issue by fireymerlin** [Shape-addons/ProfessionCooldown#18]
1x ProfessionCooldown/pcd.lua:398: attempt to index local 'skillName' (a nil value)
[string "@ProfessionCooldown/pcd.lua"]:398: in function `UpdateCharacterProfessionDb'
[string "@ProfessionCooldown/pcd.lua"]:490: in function `InitDbTable'
[string "@ProfessionCooldown/pcd.lua"]:225: in function `GetCooldownsFromSpellIds'
[string "@ProfessionCooldown/pcd.lua"]:171: in function `UpdateCds'
[string "@ProfessionCooldown/pcd.lua"]:157: in function `UpdateAndRepaintIfOpen'
[string "@ProfessionCooldown/pcd.lua"]:51: in function <ProfessionCooldown/pcd.lua:49>

**Comment by fireymerlin** [comment]
Another addon appears to have been causing the error.

**Comment by fireymerlin** [comment]
I thought another addon was causing this, but I started getting the error again.

**Comment by nieejl** [comment]
Thank you for reporting the issue.
Can you try out this build, to see if it solves the issue for you? I can't seem to reproduce the issue, but hopefully this change fixes it.

https://github.com/Shape-addons/ProfessionCooldown/blob/1-31-null-fix/ProfessionCooldown.zip

**Comment by fireymerlin** [comment]
I tried that version today after the maintenance on WOW classic and it appears to be working.
