### ISSUE TITLE
Alert when ability off CD

### ISSUE THREAD

**Issue by laurencei** [Shape-addons/ProfessionCooldown#4]
Hi,

Not sure if I missed it; is there any way to get an alert when an ability is off CD?

i.e. perhaps show up on the screen?

Otherwise I forget to check, and so I dont know when its ready?

**Comment by nieejl** [comment]
There isn't at the moment. I'll likely add this after adding filtering options and fixing some locale issues.

**Comment by nieejl** [comment]
Although many years later...
I added coloring for LDB display and the minimap button. I feel that this should be sufficient, but if not let me know.
