### ISSUE TITLE
Show/Hide Minimap Option Not Respected

### ISSUE THREAD

**Issue by crespire** [Shape-addons/ProfessionCooldown#8]
Since the update today, I have to toggle the "Show Mini Map Button" option on and off again every time I log in to have PCD remove the mini-map button, even though my preference showing correctly in the options as not checked.

The state of that preference does not seem to save properly.

**Comment by nieejl** [comment]
This is noted. I found the issue and have a fix ready that will get pushed with next version.

**Comment by nieejl** [comment]
Should be fixed in the new version (1.09)
